% heplab_about - Contact and license information
% 
% Copyright (C) 2019 Pandelis Perakakis, Granada University, peraka@ugr.es
%
% This program is free software: you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
% 
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with this program.  If not, see <https://www.gnu.org/licenses/>.

hepgui.about_string = {'HEPLAB --- Cardiac event detection for HEP analysis'; blanks(0);...
    'Pandelis Perakakis, Ph.D.'; blanks(0);...
    'Psychology, Ergonomy and Physical Activity Lab';...
    'Center of Mind, Brain and Behavior';...
    'University of Granada'; blanks(0);...
    'peraka@ugr.es';...
    'https://pandelisperakakis.info'; blanks(0);...
    'This program is free software: you can redistribute it and/or modify';...
    'it under the terms of the GNU General Public License as published by';...
    'the Free Software Foundation, either version 3 of the License, or';...
    '(at your option) any later version.'; blanks(0);...
    'This program is distributed in the hope that it will be useful,';...
    'but WITHOUT ANY WARRANTY; without even the implied warranty of';...
    'MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the';...
    'GNU General Public License for more details.';blanks(0);...
    'You should have received a copy of the GNU General Public License';...
    'along with this program.  If not, see <https://www.gnu.org/licenses/>';...
    };

hepgui.about = figure('Name','About HEPLAB',...
    'resize','off',...
    'units','characters',...
    'Position',[181 74.4 86 30.1333333333333],...
    'NumberTitle', 'off',...
    'MenuBar','none',...
    'NumberTitle','off');

movegui(hepgui.about,'center')

hepgui.about_text = uicontrol('Parent',hepgui.about,...
    'Style','text',...
    'Units','characters',...
    'FontSize',14,...
    'HorizontalAlignment','center',...
    'String',hepgui.about_string,...
    'Position',[7 3.33333333333333 71.5714285714286 23.4]);

% hepgui.about_exit = uicontrol('Parent',hepgui.about,...
%     'Style','Pushbutton',...
%     'Units','characters',...
%     'FontSize',20,...
%     'HorizontalAlignment','center',...
%     'String','Exit',...
%     'Position',[35 3 15 3],...
%     'Callback','close(hepgui.about)');
