%%
%%%%%%%%%%%%
% MAIN GUI %
%%%%%%%%%%%%

% close heplab window. There can be only one!
if exist ('hepgui','var') && isfield(hepgui,'main')
    if ishandle(hepgui.main)
        close (hepgui.main);
    end
end

% main window
hepgui.main = figure('Name','HEPLAB','resize','on','units','pixels',...
    'Position',[200,100,1024,702],'numbertitle', 'off');

% draw ECG
HEP.ecg_handle = heplab_ecgplot(HEP.ecg,HEP.srate,HEP.qrs,...
    HEP.sec_ini,HEP.ecg_handle,HEP.winsec);

%%%% SLIDER %%%%
% slider frame
hepgui.slider_fr = uicontrol('Style','frame','Position',[80 100 760 70],...
    'Visible','on',...
    'parent',hepgui.main,...
    'units','normalized',...
    'fontunits','normalized'...
    );

% min slider text
hepgui.min_slider = uicontrol('Style','text',...
    'Position',[90 140 40 20],...
    'String','Min=0s',...
    'Visible','on',...
    'parent',hepgui.main,...
    'units','normalized',...
    'fontunits','normalized');

% max slider text
hepgui.max_slider=uicontrol('Style','text',...
    'Position',[750 140 80 20],...
    'String',['Max=',num2str(HEP.ecg_dur_sec), 's'],...
    'HorizontalAlignment', 'left',...
    'parent',hepgui.main,...
    'units','normalized',...
    'fontunits','normalized');

% the slider itself!
hepgui.slider_arrow=uicontrol('Style','slider','Position',[130 140 620 20],...
    'Min',0,'Max',HEP.slider_max,...
    'Visible','on',...
    'parent',hepgui.main,...
    'units','normalized',...
    'fontunits','normalized',...
    'CallBack', [...
    'HEP.sec_ini=round(1000*get(hepgui.slider_arrow,''Value''))/1000;',...
    'HEP.ecg_handle=heplab_ecgplot(HEP.ecg,HEP.srate,HEP.qrs,',...
    'HEP.sec_ini,HEP.ecg_handle,HEP.winsec);',...
    'set(hepgui.win_label, ''String'',num2str(HEP.sec_ini));']);

%%%% CURSOR POSITION %%%%
% cursor position text
hepgui.win_txt=uicontrol('Style','text',...
    'Position',[90 110 70 20],...
    'String','Cursor Pos.:',...
    'Visible','on',...
    'parent',hepgui.main,...
    'units','normalized',...
    'fontunits','normalized');

% cursor position window
hepgui.win_label=uicontrol('Style','edit',...
    'Position',[160 110 60 20],...
    'String',num2str(HEP.sec_ini),...
    'Visible','on',...
    'parent',hepgui.main,...
    'units','normalized',...
    'fontunits','normalized',...
    'CallBack',[...
    'A=str2num(get(hepgui.win_label,''String''));',...
    'if length(A)==1,',...
        'if A(1) <= get(hepgui.slider_arrow,''Max'') & A(1)>=0,',...
            'set(hepgui.slider_arrow,''Value'',A(1));',...
        'elseif A(1)<=get(hepgui.slider_arrow,''Max'')+HEP.winsec & A(1)>=0,',...
            'set(hepgui.slider_arrow,''Value'',get(hepgui.slider_arrow,''Max''));',...
        'end,',...        
        'HEP.sec_ini=round(1000*get(hepgui.slider_arrow,''Value''))/1000;',...
        'HEP.ecg_handle=heplab_ecgplot(HEP.ecg,HEP.srate,HEP.qrs,',...
        'HEP.sec_ini,HEP.ecg_handle,HEP.winsec);',...
    'end,',...
    'set(hepgui.win_label, ''String'',num2str(HEP.sec_ini));']);

%%%% SCALEBOX %%%%
% scalebox text
hepgui.scalebox_txt=uicontrol('Style','text',...
    'Position',[400 110 70 20],...
    'String','Scale:',...
    'Visible','on',...
    'parent',hepgui.main,...
    'units','normalized',...
    'fontunits','normalized');

% scalebox
hepgui.scalebox=uicontrol('Style','edit',...
    'Position',[460 110 60 20],...
    'String','1',...
    'Visible','on',...
    'parent',hepgui.main,...
    'units','normalized',...
    'fontunits','normalized',...
    'CallBack',[...
    'A=str2num(get(hepgui.scalebox,''String''));',...
    'if length(A)==1,',...
    'HEP.ecg = HEP.ecg*A;',...
    'HEP.ecg_handle=heplab_ecgplot(HEP.ecg,HEP.srate,HEP.qrs,',...
    'HEP.sec_ini,HEP.ecg_handle,HEP.winsec);',...
    'clear A;',...
    'end,',...
    ]);

%%%% FILTER %%%%
% low cf text
hepgui.filt_low_txt=uicontrol('Style','text',...
    'Position',[600 110 70 20],...
    'String','Low cf:',...
    'Visible','on',...
    'parent',hepgui.main,...
    'units','normalized',...
    'fontunits','normalized');

% high cf text
hepgui.filt_high_txt=uicontrol('Style','text',...
    'Position',[700 110 70 20],...
    'String','High cf:',...
    'Visible','on',...
    'parent',hepgui.main,...
    'units','normalized',...
    'fontunits','normalized');

% low cf value
hepgui.filt_low_val=uicontrol('Style','edit',...
    'Position',[660 110 40 20],...
    'String','0.5',...    
    'Visible','on',...
    'parent',hepgui.main,...
    'units','normalized',...
    'fontunits','normalized');

% high cf value
hepgui.filt_high_val=uicontrol('Style','edit',...
    'Position',[760 110 40 20],...
    'String','50',...    
    'Visible','on',...
    'parent',hepgui.main,...
    'units','normalized',...
    'fontunits','normalized');

% filter button
hepgui.filt_button=uicontrol('Style','pushbutton',...
   'Position',[550 105 50 30],...
   'String','Filter',...
   'Visible','on',...
   'parent',hepgui.main,...
   'units','normalized',...
   'fontunits','normalized',...
   'CallBack',[...
   'lcf = str2num(get(hepgui.filt_low_val,''String''));',...
   'hcf = str2num(get(hepgui.filt_high_val,''String''));',...
   'HEP.ecg = heplab_ecg_filt(HEP.ecg,HEP.srate,lcf,hcf);',...
   'HEP.ecg_handle=heplab_ecgplot(HEP.ecg,HEP.srate,HEP.qrs,',...
   'HEP.sec_ini,HEP.ecg_handle,HEP.winsec);',...
   'clear A lcf hcf;',...
   ]);

%label do campo de deslocamento
hepgui.winlength_txt=uicontrol('Style','text',...
    'Position',[250 110 80 20],...
    'String','Window Length:',...
    'Visible','on',...
    'parent',hepgui.main,...
    'units','normalized',...
    'fontunits','normalized');

%botao que desloca uma janela para esquerda
hepgui.lft_arrow=uicontrol('Style','pushbutton',...
    'String','<',...
    'Position',[330 110 20 20],...
    'Visible','on',...
    'parent',hepgui.main,...
    'units','normalized',...
    'fontunits','normalized',...
    'Callback',[...
    'if HEP.sec_ini-HEP.winsec >= 0,',...
    'HEP.sec_ini=HEP.sec_ini-HEP.winsec;',...
    'else,',...
    'HEP.sec_ini=0;',...
    'end,',...
    'set(hepgui.slider_arrow,''Value'',HEP.sec_ini);',...
    'HEP.ecg_handle=heplab_ecgplot(HEP.ecg,HEP.srate,HEP.qrs,HEP.sec_ini,',...
    'HEP.ecg_handle,HEP.winsec);',...
    'set(hepgui.win_label, ''String'',num2str(HEP.sec_ini));']);

%text edit para determinar o tamanho da janela de deslocamento
hepgui.winlength_label=uicontrol('Style','edit',...
    'Position',[350 110 40 20],...
    'Value', HEP.winsec,...
    'String',num2str(HEP.winsec),...
    'Visible','on',...
    'parent',hepgui.main,...
    'units','normalized',...
    'fontunits','normalized',...
    'Callback',[...
    'A=str2num(get(hepgui.winlength_label,''String''));',...
    'if (length(A)==1) & (A(1) >= 1/HEP.srate) & (A<=HEP.ecg_dur_sec),',...
    'HEP.winsec=round(1000*A(1))/1000;',...
    'if A(1)+HEP.sec_ini>=HEP.ecg_dur_sec,',...
    'HEP.sec_ini=HEP.ecg_dur_sec-HEP.winsec;',...
    'set(hepgui.win_label,''String'',num2str(HEP.sec_ini));',...
    'set(hepgui.slider_arrow,''Value'',HEP.sec_ini);',...
    'end,',...
    'if HEP.ecg_dur_sec-HEP.winsec > 0,',...
    'set(hepgui.slider_arrow,''Max'',HEP.ecg_dur_sec-HEP.winsec);',...
    'else,',...
    'set(hepgui.slider_arrow,''Max'',0);',...
    'end,',...
    'HEP.ecg_handle=heplab_ecgplot(HEP.ecg,HEP.srate,HEP.qrs,HEP.sec_ini,',...
    'HEP.ecg_handle,HEP.winsec);',...
    'end,',...
    'set(hepgui.winlength_label,''String'',num2str(HEP.winsec));',...
    ]);

%botao que desloca uma janela para direita
hepgui.rgt_arrow=uicontrol('Style','pushbutton',...
    'String','>',...
    'Position',[390 110 20 20],...
    'Visible','on',...
    'parent',hepgui.main,...
    'units','normalized',...
    'fontunits','normalized',...
    'Callback',[...
    'if HEP.sec_ini+HEP.winsec <= get(hepgui.slider_arrow,''Max''),',...
    'HEP.sec_ini=HEP.sec_ini+HEP.winsec;',...
    'else,',...
    'HEP.sec_ini=get(hepgui.slider_arrow,''Max'');',...
    'end,',...
    'set(hepgui.slider_arrow,''Value'',HEP.sec_ini);',...
    'HEP.ecg_handle=heplab_ecgplot(HEP.ecg,HEP.srate,HEP.qrs,HEP.sec_ini,',...
    'HEP.ecg_handle,HEP.winsec);',...
    'set(hepgui.win_label, ''String'',num2str(HEP.sec_ini));']);


%borda em volta da caixa de texto de mensagens 
%hepgui.message_fr=uicontrol('Style','frame','Position',[590 20 250 60]);
   
%caixa de texto para mensagens 'deteccao em andamento'
% hepgui.message_txt=uicontrol('Style','text',...
%    'Position',[600 30 230 40],...
%    'String', ' ');   

hepgui.preview_btn=uicontrol('Style','pushbutton',...
    'String','PREVIEW',...
    'Position',[860 105 110 60],...
    'Visible','on',...
    'parent',hepgui.main,...
    'units','normalized',...
    'fontunits','normalized',...
    'CallBack',[...
    'if ~isempty(HEP.qrs),',...
        'heplab_preview_rr;',...
    'else,',...
        'errordlg(''No QRS events available!'');',...
    'end,',...
    ]);

hepgui.save_btn=uicontrol('Style','pushbutton',...
    'String','SAVE',...
    'Position',[860 20 110 60],...
    'Visible','on',...
    'parent',hepgui.main,...
    'units','normalized',...
    'fontunits','normalized',...
    'CallBack',[...
    'if ~isempty(HEP.qrs),',...
        'heplab_save_qrs;',...
    'else,',...
        'errordlg(''No QRS events available!'');',...
    'end,',...
    ]);


%%%%%%%%%%
%os cliques no HEP.ecg apagam ou fazem marcacoes R
set(hepgui.main, 'WindowButtonDownfcn',[...
    '[HEP.qrs]=heplab_edit_qrs(HEP.ecg,HEP.srate,HEP.qrs,HEP.ecg_handle,',...
    'HEP.sec_ini,HEP.winsec,HEP.ecg_dur_sec);',...
    'HEP.ecg_handle=heplab_ecgplot(HEP.ecg,HEP.srate,HEP.qrs,',...
    'HEP.sec_ini,HEP.ecg_handle,HEP.winsec);',...
    ]);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%5
%
% MENU
%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%neste menu, aparecem algumas funcoes relacioandas com o intervalo R-R deste HEP.ecg
hepgui.menu_iRR=uimenu(hepgui.main,'Label','HEPLAB');

%submenu para detectar a onda R
hepgui.subm_qrs_detect=uimenu(hepgui.menu_iRR,'Label','Detect R waves');

%submenu para detectar a onda R pelo algoritmo rapido
hepgui.subm_qrs_detect_rapido=uimenu(hepgui.subm_qrs_detect,'Label','Fast algorithm',...
    'CallBack',	[...
    'HEP.qrs = heplab_qrs_fastdetect(HEP.ecg,HEP.srate);'...
    'HEP.ecg_handle=heplab_ecgplot(HEP.ecg,HEP.srate,HEP.qrs,HEP.sec_ini,',...
    'HEP.ecg_handle,HEP.winsec);']);

% hepgui.subm_qrs_detect_rapido=uimenu(hepgui.menu_iRR,'Label',...
%     'en el laboratorio roque vino el doctor malevolo para atacar a los del laboratorio.');

%submenu para detectar a onda R pelo algoritmo lento
hepgui.subm_qrs_detect_lento=uimenu(hepgui.subm_qrs_detect,'Label','Slow algorithm',...
    'CallBack',	[...
    'HEP.qrs = heplab_qrs_slowdetect(HEP.ecg,HEP.srate);'...
    'HEP.ecg_handle=heplab_ecgplot(HEP.ecg,HEP.srate,HEP.qrs,HEP.sec_ini,',...
    'HEP.ecg_handle,HEP.winsec);']);

hepgui.subm_qrs_detect_pan_tompkin=uimenu(hepgui.subm_qrs_detect,'Label','Pan-Tompkin algorithm',...
    'CallBack',	[...
    '[amp,HEP.qrs] = heplab_qrs_detect_pan_tompkin(HEP.ecg,HEP.srate);'...
    'if size(HEP.qrs,1)<size(HEP.qrs,2); HEP.qrs = HEP.qrs''; end;'...
    'HEP.ecg_handle=heplab_ecgplot(HEP.ecg,HEP.srate,HEP.qrs,HEP.sec_ini,',...
    'HEP.ecg_handle,HEP.winsec);']);

hepgui.subm_qrs_detect_twave=uimenu(hepgui.subm_qrs_detect,'Label','T wave',...
    'CallBack',	[...
    '[R,Q,S,T,P_w] = heplab_T_detect_MTEO(HEP.ecg,HEP.srate,0);'...
    'HEP.qrs = T(:,1);'...
    'HEP.ecg_handle=heplab_ecgplot(HEP.ecg,HEP.srate,HEP.qrs,HEP.sec_ini,',...
    'HEP.ecg_handle,HEP.winsec);'...
    'clear R Q S T P_w']);

hepgui.subm_reload_ecg=uimenu(hepgui.menu_iRR,'Label','Reload ECG from EEG structure',...
    'CallBack','pop_heplab');

hepgui.subm_clear_ecg=uimenu(hepgui.menu_iRR,'Label','Clear events',...
'CallBack',	[...
    'if isfield(HEP,''qrs'') && ~isempty(HEP.qrs),',...
        'HEP.qrs = [];',...
        'HEP.ecg_handle=heplab_ecgplot(HEP.ecg,HEP.srate,HEP.qrs,HEP.sec_ini,',...
            'HEP.ecg_handle,HEP.winsec);',...
    'else,',...
        'errordlg (''No events found!'');',...
    'end,',...
    ]);
       
hepgui.subm_save_hep=uimenu(hepgui.menu_iRR,'Label','Save HEP structure',...
    'Callback', [...
    'HEP.savefilename = inputdlg(''Select a name for your HEP variable'','...
    '''Save HEP'');',...
    'save([HEP.savefilename{1} ''.mat''],''HEP'');'...    
    ]);

hepgui.subm_load_hep=uimenu(hepgui.menu_iRR,'Label','Load HEP structure',...
    'CallBack',	[...
    '[file, path] = uigetfile (''*.mat'','...
    '''Select the .mat file containing the HEP variable'');',...
    'load([path file]);'...
    'if isstruct(HEP),'...        
        'heplab_main;',...
    'else,',...
        'errordlg(''No HEP variable found'');',...
    'end,',...    
    ]);